# Generated by Django 4.0.1 on 2022-02-03 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
