# Generated by Django 4.0.1 on 2022-02-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_delete_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='age',
            field=models.BooleanField(default=True),
        ),
    ]
