# Generated by Django 4.0.1 on 2022-02-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_alter_destination_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='age',
            field=models.IntegerField(default=True),
        ),
    ]
