# Generated by Django 4.0.1 on 2022-02-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
