# Generated by Django 4.0.1 on 2022-02-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
