# Generated by Django 4.0.1 on 2022-02-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='age',
            new_name='phone',
        ),
    ]
