# Generated by Django 4.0.1 on 2022-02-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone',
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(default='21'),
        ),
    ]
