# Generated by Django 4.0.1 on 2022-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_phone_account_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('country', models.CharField(choices=[('IN', 'India'), ('US', 'United States.')], default='IN', max_length=2)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
    ]
