# Generated by Django 4.0.1 on 2022-02-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_contact_contactdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='country',
            field=models.CharField(choices=[('India', 'IN'), ('United States', 'US')], default='IN', max_length=20),
        ),
    ]
