# Generated by Django 4.0.1 on 2022-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_contactdetails_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
