# Generated by Django 4.0.1 on 2022-02-21 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_contactdetails_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdetails',
            old_name='id',
            new_name='contactid',
        ),
    ]
